require "mini_twin"
require "fileutils"

namespace :mini_twin do
  desc "Generate RBS signatures for all loaded MiniTwin subclasses into sig/generated/ " \
       "(override output dir with OUTPUT_DIR env var or task argument)"
  task :generate_rbs, [:output_dir] do |_t, args|
    output_dir = args[:output_dir] || ENV.fetch("MINI_TWIN_RBS_DIR", "sig/generated")

    twins = MiniTwin.__descendants__.select(&:name).sort_by(&:name)

    if twins.empty?
      warn "[mini-twin] No MiniTwin subclasses found. " \
           "Ensure your classes are loaded before running this task."
      next
    end

    twins.each do |klass|
      file_path = klass.name
        .gsub("::", "/")
        .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
        .gsub(/([a-z\d])([A-Z])/, '\1_\2')
        .downcase
        .concat(".rbs")

      output_path = File.join(output_dir, file_path)
      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, "# Generated by mini-twin. DO NOT EDIT.\n\n#{klass.to_rbs}\n")
      puts "  [mini-twin] #{output_path}"
    end
  end
end
