require "mini_twin"
require "fileutils"

namespace :minitwin do
  desc "Generate RBS signatures for all loaded Minitwin subclasses into sig/generated/ " \
       "(override output dir with OUTPUT_DIR env var or task argument)"

  task :generate_rbs, [:output_dir] do |_t, args|
    # In Rails, invoke :environment to ensure the app is fully initialized
    # before eager loading. We invoke it here rather than declaring it as a
    # prerequisite because Rails defines :environment *after* running railtie
    # rake_tasks blocks, so Rake::Task.task_defined?(:environment) is always
    # false at rake file load time.
    Rake::Task[:environment].invoke if Rake::Task.task_defined?(:environment)

    # Eager load the rails app if the task runs in Rails context
    Rails.application.eager_load! if defined?(Rails)

    # Require files "manually" in non-rails projects.
    # Provide pattern for file paths as ENV var:
    #
    # MINITWIN_REQUIRE_GLOB="lib/**/*.rb" rake minitwin:generate_rbs
    #
    if (glob = ENV.fetch("MINITWIN_REQUIRE_GLOB", nil))
      Dir[glob].each { |f| require File.expand_path(f) }
    end

    output_dir = args[:output_dir] || ENV.fetch("MINITWIN_RBS_DIR", "sig/generated")

    twins = Minitwin.__descendants__.select(&:name).sort_by(&:name)

    if twins.empty?
      warn "[minitwin] No Minitwin subclasses found. " \
           "Ensure your classes are loaded before running this task."
      next
    end

    twins.each do |klass|
      file_path = klass.name
        .gsub("::", "/")
        .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
        .gsub(/([a-z\d])([A-Z])/, '\1_\2')
        .downcase
        .concat(".rbs")

      output_path = File.join(output_dir, file_path)
      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, "# Generated by minitwin. DO NOT EDIT.\n\n#{klass.to_rbs}\n")
      puts "  [minitwin] #{output_path}"
    end
  end
end
