# frozen_string_literal: true

require_relative "../minitwin"
require "fileutils"

namespace :minitwin do
  desc "Generate RBS signatures for all loaded Minitwin subclasses into sig/generated/ " \
    "(override output dir with OUTPUT_DIR env var or task argument)"

  task :generate_rbs, [:output_dir] do |_t, args|
    # In Rails, invoke :environment to ensure the app is fully initialized
    # before eager loading. We invoke it here rather than declaring it as a
    # prerequisite because Rails defines :environment *after* running railtie
    # rake_tasks blocks, so Rake::Task.task_defined?(:environment) is always
    # false at rake file load time.
    Rake::Task[:environment].invoke if Rake::Task.task_defined?(:environment)

    # Eager load the rails app if the task runs in Rails context
    Rails.application.eager_load! if defined?(Rails)

    # Require files "manually" in non-rails projects.
    # Provide pattern for file paths as ENV var:
    #
    # MINITWIN_REQUIRE_GLOB="lib/**/*.rb" rake minitwin:generate_rbs
    #
    if (glob = ENV.fetch("MINITWIN_REQUIRE_GLOB", nil))
      Dir[glob].each { |f| require File.expand_path(f) }
    end

    output_dir = args[:output_dir] || ENV.fetch("MINITWIN_RBS_DIR", "sig/generated")

    twins = Minitwin.__descendants__.select(&:name).sort_by(&:name)

    if twins.empty?
      warn "[minitwin] No Minitwin subclasses found. " \
        "Ensure your classes are loaded before running this task."
      next
    end

    twins.each do |klass|
      file_path = klass.name.
                    gsub("::", "/").
                    gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').
                    gsub(/([a-z\d])([A-Z])/, '\1_\2').
                    downcase.
                    concat(".rbs")

      output_path = File.join(output_dir, file_path)
      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, "# Generated by minitwin. DO NOT EDIT.\n\n#{klass.to_rbs}\n")
      puts "  [minitwin] #{output_path}"
    end
  end

  desc "Generate rbi/minitwin.rbi from the RBS signatures in sig/generated for Sorbet consumers " \
    "(override output with MINITWIN_RBI_OUT or task argument)"
  task :generate_rbi, [:output] do |_t, args|
    output = args[:output] || ENV.fetch("MINITWIN_RBI_OUT", "rbi/minitwin.rbi")

    # sig/module.rbs is a local shim for dry-types, not part of minitwin's
    # public API, so it must not leak into the RBI we ship.
    paths = Dir["sig/generated/**/*.rbs"]

    if paths.empty?
      warn "[minitwin] No RBS signatures in sig/generated. Run: bundle exec rbs-inline --output lib"
      next
    end

    FileUtils.mkdir_p(File.dirname(output))
    File.write(
      output,
      Minitwin::Rbi.from_rbs_files(paths, extended_modules: Minitwin::Rbi.extended_modules(Minitwin))
    )
    puts "  [minitwin] #{output} (#{paths.size} RBS files)"
  end

  desc "Check that generated RBS signatures are up to date"
  task :check_rbs do
    FileUtils.rm_rf(Dir["sig/generated/**/*.rbs"])
    sh "bundle exec rbs-inline --output lib"

    diff = `git diff --name-only sig/generated`
    untracked = `git ls-files --others --exclude-standard sig/generated`

    unless diff.empty? && untracked.empty?
      warn "[minitwin] RBS signatures are out of date. Run: bundle exec rbs-inline --output lib"
      warn diff unless diff.empty?
      warn untracked unless untracked.empty?
      exit 1
    end
  end

  desc "Check that rbi/minitwin.rbi is up to date"
  task :check_rbi do
    expected = Minitwin::Rbi.from_rbs_files(
      Dir["sig/generated/**/*.rbs"],
      extended_modules: Minitwin::Rbi.extended_modules(Minitwin)
    )

    if !File.exist?("rbi/minitwin.rbi") || File.read("rbi/minitwin.rbi") != expected
      warn "[minitwin] rbi/minitwin.rbi is out of date. Run: rake minitwin:generate_rbi"
      exit 1
    end
  end
end
