stages:
  - lint
  - test

variables:
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: "4"
  BUNDLE_RETRY: "3"
  RAILS_ENV: test

test:
  stage: test
  image: ruby:${RUBY_VERSION}-slim
  interruptible: true
  parallel:
    matrix:
      - RUBY_VERSION: ["3.3", "3.4", "4.0"]
  cache:
    key: ruby-${RUBY_VERSION}
    paths:
      - vendor/bundle
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends build-essential pkg-config
    - gem install bundler -N || true
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
  script:
    - bundle exec rake test

lint:
  stage: lint
  image: ruby:4.0-slim
  interruptible: true
  cache:
    key: ruby-4.0
    paths:
      - vendor/bundle
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends build-essential pkg-config
    - gem install bundler -N || true
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
  script:
    - bundle exec rubocop

check_rbs:
  stage: lint
  image: ruby:4.0-slim
  interruptible: true
  cache:
    key: ruby-4.0
    paths:
      - vendor/bundle
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends build-essential pkg-config git
    - gem install bundler -N || true
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
  script:
    - bundle exec rake minitwin:check_rbs
