require "json"
require "zeitwerk"
begin
  require "dry-types"
rescue LoadError
end
require_relative "mini_twin/version"

begin
  require "active_model"
rescue LoadError
end

# Setup Zeitwerk loader for the gem to support Rails autoloading
loader = Zeitwerk::Loader.for_gem
# Ignore the Bundler auto-require shim file (lib/minitwin.rb), which does not
# follow Zeitwerk's constant naming conventions.
begin
  loader.ignore(File.join(__dir__, "mini-twin.rb"))
rescue NoMethodError
  # Older Zeitwerk versions may not support ignore here; safe to skip.
end
loader.inflector.inflect(
  "mini_twin" => "Minitwin"
)
loader.setup

class Minitwin
  # Constants for internal variable naming
  INTERNAL_MODEL_PREFIX = "@internal_model__"
  NESTED_READER_PREFIX = "__nested_read__"
  DYNAMIC_ALIASES_VAR = "@__dynamic_aliases__"
  DYNAMIC_ALIASES_REV_VAR = "@__dynamic_aliases_rev__"

  # Shared utility methods
  module Utils
    module_function

    # Normalize property name to instance variable name (handles ? suffix)
    def ivar_name(name)
      "@#{name}".delete_suffix("?")
    end

    # Convert instance variable to attribute key symbol
    def ivar_to_key(ivar)
      ivar.to_s.delete_prefix("@").to_sym
    end

    # Traverse a nested path on an object
    def traverse_path(obj, path)
      path.each { |seg| obj = obj.public_send(seg) }
      obj
    end
  end

  include ActiveModel::Model if defined?(ActiveModel::Model)
  include Minitwin::Initialization
  include Minitwin::Assignment
  include Minitwin::Serialization
  include Minitwin::Sync
  extend  Minitwin::ClassMethods

  # Lazy-memoized lookups for late-loaded optional deps (Dry::Types,
  # ActiveSupport's HashWithIndifferentAccess). Resolved on first call so
  # boot-order between minitwin and the deps does not matter.
  class << self
    def hash_klass
      @hash_klass ||= defined?(HashWithIndifferentAccess) ? HashWithIndifferentAccess : Hash
    end

    private

    def coercion_error_classes
      @coercion_error_classes ||= begin
        arr = [TypeError, ArgumentError]
        arr.unshift(::Dry::Types::CoercionError) if defined?(::Dry::Types::CoercionError)
        arr.freeze
      end
    end

    def active_model_initialized?(klass)
      return false unless defined?(ActiveModel::API) || defined?(ActiveModel::Model)
      ancestors = klass.ancestors
      (defined?(ActiveModel::API) && ancestors.include?(ActiveModel::API)) ||
        (defined?(ActiveModel::Model) && ancestors.include?(ActiveModel::Model))
    end
  end

  # Track descendants via WeakMap so anonymous subclasses can be GC'd.
  # The map lives only on Minitwin itself; subclasses' inherited hooks
  # delegate up so that deep hierarchies still register on the root.
  @__descendants_map__ = ObjectSpace::WeakMap.new
  class << self
    def __descendants__
      Minitwin.instance_variable_get(:@__descendants_map__).keys
    end

    def inherited(sub)
      Minitwin.instance_variable_get(:@__descendants_map__)[sub] = true
      super
    end
  end
end

# Optional: Generate RBS on exit when configured via ENV.
if ENV["MINITWIN_RBS_OUT"] && !ENV["MINITWIN_RBS_OUT"].empty?
  at_exit do
    require "fileutils"
    path = ENV["MINITWIN_RBS_OUT"]
    begin
      twins = Minitwin.__descendants__.select { |k| k.name }
      content = String.new
      content << "# This file is generated by minitwin. DO NOT EDIT.\n"
      content << "# Generated at: #{Time.now}\n\n"
      twins.sort_by!(&:name)
      twins.each do |k|
        content << k.to_rbs
        content << "\n\n"
      end
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, content)
    rescue => e
      warn "[minitwin] Failed to generate RBS: #{e.class}: #{e.message}"
    end
  end
end

require "mini_twin/railtie" if defined?(Rails::Railtie)
# Minitwin
# --------
# Entry point that wires together the core modules and conditionally enables
# ActiveModel integration when it is available. The goal is to keep runtime
# dependencies minimal while providing a clean DSL for twin/presenter objects.
# See docs/ARCHITECTURE.md for an overview.

# Backward-compatible alias. References to `MiniTwin` continue to work but
# emit Ruby's standard deprecation warning (gated by Warning[:deprecated]).
MiniTwin = Minitwin
Object.deprecate_constant(:MiniTwin)
