require "json"
require "set"
require "fileutils"
require "zeitwerk"
begin
  require "dry-types"
rescue LoadError
end
require_relative "mini_twin/version"

begin
  require "active_model"
rescue LoadError
end

# Setup Zeitwerk loader for the gem to support Rails autoloading
loader = Zeitwerk::Loader.for_gem
# Ignore the Bundler auto-require shim file (lib/mini-twin.rb), which does not
# follow Zeitwerk's constant naming conventions.
begin
  loader.ignore(File.join(__dir__, "mini-twin.rb"))
rescue NoMethodError
  # Older Zeitwerk versions may not support ignore here; safe to skip.
end
loader.inflector.inflect(
  "mini_twin" => "MiniTwin"
)
loader.setup

class MiniTwin
  # Constants for internal variable naming
  INTERNAL_MODEL_PREFIX = "@internal_model__"
  NESTED_READER_PREFIX = "__nested_read__"
  DYNAMIC_ALIASES_VAR = "@__dynamic_aliases__"
  DYNAMIC_ALIASES_REV_VAR = "@__dynamic_aliases_rev__"

  # Shared utility methods
  module Utils
    module_function

    # Normalize property name to instance variable name (handles ? suffix)
    def ivar_name(name)
      "@#{name}".delete_suffix("?")
    end

    # Convert instance variable to attribute key symbol
    def ivar_to_key(ivar)
      ivar.to_s.delete_prefix("@").to_sym
    end

    # Traverse a nested path on an object
    def traverse_path(obj, path)
      path.each { |seg| obj = obj.public_send(seg) }
      obj
    end
  end

  include ActiveModel::Model if defined?(ActiveModel::Model)
  include MiniTwin::Initialization
  include MiniTwin::Assignment
  include MiniTwin::Serialization
  include MiniTwin::Sync
  extend  MiniTwin::ClassMethods

  # Track descendants to allow RBS generation for all loaded twins
  @__descendants__ = []
  class << self
    attr_reader :__descendants__

    def inherited(sub)
      begin
        MiniTwin.__descendants__ << sub
      rescue FrozenError
        # Ignore if descendants array is frozen
      end
      super
    end
  end
end

# Optional: Generate RBS on exit when configured via ENV.
if ENV["MINI_TWIN_RBS_OUT"] && !ENV["MINI_TWIN_RBS_OUT"].empty?
  at_exit do
    path = ENV["MINI_TWIN_RBS_OUT"]
    begin
      twins = MiniTwin.__descendants__.select { |k| k.name }
      content = String.new
      content << "# This file is generated by mini-twin. DO NOT EDIT.\n"
      content << "# Generated at: #{Time.now}\n\n"
      twins.sort_by!(&:name)
      twins.each do |k|
        content << k.to_rbs
        content << "\n\n"
      end
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, content)
    rescue => e
      warn "[mini-twin] Failed to generate RBS: #{e.class}: #{e.message}"
    end
  end
end

require "mini_twin/railtie" if defined?(Rails::Railtie)
# MiniTwin
# --------
# Entry point that wires together the core modules and conditionally enables
# ActiveModel integration when it is available. The goal is to keep runtime
# dependencies minimal while providing a clean DSL for twin/presenter objects.
# See docs/ARCHITECTURE.md for an overview.
