require "json"
require "set"
require "fileutils"
require "dry-types"
require "active_support/core_ext/object/blank"
require "active_support/core_ext/hash/indifferent_access"
require "active_support/hash_with_indifferent_access"

begin
  require "active_model"
rescue LoadError
end

require_relative "mini_twin/version"
require_relative "mini_twin/types"
require_relative "mini_twin/initialization"
require_relative "mini_twin/assignment"
require_relative "mini_twin/serialization"
require_relative "mini_twin/class_methods"

class MiniTwin
  include ActiveModel::Model if defined?(ActiveModel::Model)
  include MiniTwin::Initialization
  include MiniTwin::Assignment
  include MiniTwin::Serialization
  extend  MiniTwin::ClassMethods

  # Track descendants to allow RBS generation for all loaded twins
  @__descendants__ = []
  class << self
    attr_reader :__descendants__

    def inherited(sub)
      (__descendants__ << sub) rescue nil
      super
    end
  end
end

# Optional: Generate RBS on exit when configured via ENV.
if ENV["MINI_TWIN_RBS_OUT"].present?
  at_exit do
    path = ENV["MINI_TWIN_RBS_OUT"]
    begin
      twins = MiniTwin.__descendants__.select { |k| k.name }
      content = String.new
      content << "# This file is generated by mini-twin. DO NOT EDIT.\n"
      content << "# Generated at: #{Time.now}\n\n"
      twins.sort_by!(&:name)
      twins.each do |k|
        content << k.to_rbs
        content << "\n\n"
      end
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, content)
    rescue => e
      warn "[mini-twin] Failed to generate RBS: #{e.class}: #{e.message}"
    end
  end
end
# MiniTwin
# --------
# Entry point that wires together the core modules and conditionally enables
# ActiveModel integration when it is available. The goal is to keep runtime
# dependencies minimal while providing a clean DSL for twin/presenter objects.
# See docs/ARCHITECTURE.md for an overview.
